<?php
/**
 * @file
 * Code for the Cluster Events feature.
 */

include_once 'cluster_events.features.inc';
include_once 'cluster_events.pathauto.inc';

const CLUSTER_EVENTS_PER_PAGE = 10;

/**
 *  Implements hook_menu().
 */
function cluster_events_menu() {
  $items['node/%/events'] = array(
    'title' => 'events',
    'title callback' => '_cluster_events_title_callback',
    'title arguments' => array(1),
    'page callback' => 'cluster_events_all',
    'page arguments' => array(1),
    'access callback' => 'og_is_group',
    'access arguments' => array(0, 1),
    'type' => MENU_CALLBACK,
  );

  $items['events'] = array(
    'title' => 'All events',
    'page callback' => 'cluster_events_all',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu title callback.
 */
function _cluster_events_title_callback($nid) {
  global $language;
  $title = t('Events');
  if (! is_numeric($nid)) {
    return $title;
  }

  try {
    // @TODO manage multilinigual loading of entities.
    $wrapper = entity_metadata_wrapper('node', node_load($nid), array('langcode' => LANGUAGE_NONE));
    return $wrapper->label();
  }
  catch (EntityMetadataWrapperException $exc) {
    _log_entity_metadata_wrapper_error($exc, 'cluster_context');
  }
  return $title;
}

/**
 * Page callback, lists of events using Search API.
 * @param $nid, if present, limit events that are part of group id audience.
 * @return Render array
 */
function cluster_events_all($nid) {

  // Filter by event date with entity field query.
  $filter_by_date = new EntityFieldQuery();
  $filter_by_date->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldOrderBy('field_recurring_event_date', 'value', 'DESC');

  $filter_by_date_count = new EntityFieldQuery();
  $filter_by_date_count->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldOrderBy('field_recurring_event_date', 'value', 'DESC')
    ->count();

  if ($nid) {
    $filter_by_date->fieldCondition('og_group_ref', 'target_id', $nid);
    $filter_by_date_count->fieldCondition('og_group_ref', 'target_id', $nid);
  }

  $number_of_results = $filter_by_date_count->execute();

  $offset = pager_find_page() * CLUSTER_EVENTS_PER_PAGE;
  $filter_by_date->range($offset, CLUSTER_EVENTS_PER_PAGE);

  // Execute query to filter by event date.
  $query_date_filter_results = $filter_by_date->execute();

  pager_default_initialize($number_of_results, CLUSTER_EVENTS_PER_PAGE);

  if (! $query_date_filter_results['node']) {
    $content = array(
      '#markup' => t('No events scheduled at the moment.'),
    );
  }
  else {
    $content = array(
      "#theme" => 'cluster_og_all_events',
      '#events' => array(),
    );
    $nids = array_keys($query_date_filter_results['node']);
    $content['#events'] = cluster_events_format_list($nids);
  }

  $ret['content'] = $content;
  $ret['pager'] = array(
    '#theme' => 'pager',
  );

  return $ret;
}

function cluster_events_upcoming() {
  $query = new EntityFieldQuery();
  $results = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->fieldCondition('field_recurring_event_date', 'value', date('Y-m-d'), '>')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldOrderBy('field_recurring_event_date', 'value', 'ASC')
    ->range(0, 3)
    ->execute();

  if (!isset($results['node'])) {
    return FALSE;
  }

  $nids = array_keys($results['node']);

  $entities = entity_load('node', $nids);
  $events = array();
  foreach ($entities as $entity) {
    $events[] = cluster_events_format_upcoming($entity->nid);
  }

  return theme('cluster_og_upcoming_events', array(
    'events' => $events,
    'all_events_link' => '/events',
    'global_events_link' => array(
      '#type' => 'link',
      '#href' => 'geographic-region/global/events',
      '#title' => 'See Global Events',
    ),
  ));
}

function cluster_events_format_upcoming($nid) {
  $node = node_load($nid);
  if (!$node || $node->type != 'event') {
    return FALSE;
  }

  try {
    $wrapper = entity_metadata_wrapper('node', $node);

    // Render the date as per the teaser field display setting.
    $date = field_view_field('node', $node, 'field_recurring_event_date', 'teaser');

    $geo = $wrapper->field_coordinates->value();
    $map_link = l(t('map'), 'https://www.google.ca/maps/place/' . $geo['lat'] . ',' . $geo['lon'] . '/@' . $geo['lat'] . ',' . $geo['lon'] . ',15z', array(
      'attributes' => array(
        'target' => '_blank',
      )
    ));

    // Get contact(s).
    $contacts = $wrapper->field_event_contact->value();
    $contact_list = cluster_events_get_contact_list($contacts);

    $static_map = FALSE;
    if (!empty($geo)) {
      $static_map_url = 'http://maps.googleapis.com/maps/api/staticmap?center=' . $geo['lat'] . ',' . $geo['lon'] . '&zoom=15&scale=1&size=300x200&maptype=roadmap&format=png&visual_refresh=true&markers=size:small|color:0x000000|label:1|' . $geo['lat'] . ',' . $geo['lon'];
      $static_map_description = 'Map to ' . $wrapper->title->value();
      $static_map = theme('image', array(
        'path' => $static_map_url,
        'alt' => t($static_map_description),
        'title' => t($static_map_description),
      ));
    }

    return array(
      'date' => $date,
      'title' => $wrapper->title->value(),
      'link' => l($wrapper->title->value(), 'node/' . $node->nid),
      'location' => field_view_field('node', $node, 'field_postal_address', 'teaser'),
      'map_link' => $map_link,
      'static_map' => FALSE,
      'contact' => $contact_list,
    );
  }
  catch (EntityMetadataWrapperException $exception) {
    _log_entity_metadata_wrapper_error($exception, 'cluster_events');
  }
}

function cluster_events_format_list($nids) {
  $events = array();
  foreach ($nids as $nid) {
    $node = node_load($nid);
    if (!$node || $node->type != 'event') {
      return FALSE;
    }

    try {
      $wrapper = entity_metadata_wrapper('node', $node);
      $value = $wrapper->field_recurring_event_date->value();
      $event_date = $value[0];
      $current_date = time();
      $is_future = $event_date > $current_date ? TRUE : FALSE;
      $is_past = !$is_future;

      // Render the date as per the teaser field display setting.
      $date = field_view_field('node', $node, 'field_recurring_event_date', 'teaser');

      $geo = $wrapper->field_coordinates->value();
      $map_url = 'https://www.google.ca/maps/place/' . $geo['lat'] . ',' . $geo['lon'] . '/@' . $geo['lat'] . ',' . $geo['lon'] . ',15z';
      $map_link = l(t('map'), $map_url, array(
        'attributes' => array(
          'target' => '_blank',
        )
      ));

      // Get contact(s).
      $contacts = $wrapper->field_event_contact->value();
      $contact_list = cluster_events_get_contact_list($contacts);

      $static_map = cluster_events_create_map_with_link($geo, $wrapper->title->value());

      $events[] = array(
        'is_future' => $is_future,
        'is_past' => $is_past,
        'date' => $date,
        'title' => t($wrapper->title->value()),
        'link' => l($wrapper->title->value(), 'node/' . $node->nid),
        'location' => field_view_field('node', $node, 'field_postal_address', 'teaser'),
        'map_link' => $map_link,
        'static_map' => $static_map,
        'contact' => $contact_list,
        'description' => field_view_field('node', $node, 'body', 'teaser'),
      );
    }
    catch (EntityMetadataWrapperException $exception) {
      _log_entity_metadata_wrapper_error($exception, 'cluster_events');
    }
  }
  return $events;
}

/**
 * Implements hook_preprocess_node().
 */
function cluster_events_preprocess_node(&$variables) {
  if ($variables['type'] == 'event') {
    $variables['static_map'] = FALSE;
    $variables['map_link'] = FALSE;
    try {
      $wrapper = entity_metadata_wrapper('node', $variables['node']);
      $geo = $wrapper->field_coordinates->value();

      // Get contact(s).
      $contacts = $wrapper->field_event_contact->value();
      $contact_list = cluster_events_get_contact_list($contacts);

      // Replace the field with our custom contact list.
      if ($contact_list) {
        $variables['content']['field_event_contact'] = array(
          '#weight' => 2,
          '#markup' => $contact_list,
          '#prefix' => '<div class="field"><div class="field-label">Contact:&nbsp;</div>',
          '#suffix' => '</div></div>'
        );
      }

      // Static map image.
      $variables['static_map'] = cluster_events_create_map_with_link($geo, $wrapper->title->value());
    }
    catch (EntityMetadataWrapperException $exception) {
      _log_entity_metadata_wrapper_error($exception, 'cluster_events');
    }
  }
}

/**
 * Returns a map linking back to the Google maps.
 */
function cluster_events_create_map_with_link($geo = NULL, $map_title = '') {
  $static_map = FALSE;
  if (!empty($geo)) {
    $map_url = 'https://www.google.ca/maps/place/' . $geo['lat'] . ',' . $geo['lon'] . '/@' . $geo['lat'] . ',' . $geo['lon'] . ',15z';
    $static_map_url = 'http://maps.googleapis.com/maps/api/staticmap?center=' . $geo['lat'] . ',' . $geo['lon'] . '&zoom=15&scale=1&size=300x200&maptype=roadmap&format=png&visual_refresh=true&markers=size:small|color:0x000000|label:1|' . $geo['lat'] . ',' . $geo['lon'];
    $static_map_description = t('Map to ') . $map_title;
    $static_map = theme('image', array(
      'path' => $static_map_url,
      'alt' => $static_map_description,
      'title' => $static_map_description,
    ));
    $static_map = l($static_map, $map_url, array('html' => TRUE, 'attributes' => array('target' => '_blank')));
  }
  return $static_map;
}

/**
 * Returns a list of contact links.
 */
function cluster_events_get_contact_list($contacts = FALSE) {
  $contact_list = FALSE;

  if (!empty($contacts)) {
    $contact_email = '';
    $last_contact = count($contacts) - 1;
    // Get all the contacts and email address.
    foreach ($contacts as $index => $contact) {
      $separator = ", ";
      if ($index == $last_contact) {
        $separator = '';
      }
      $contact_name = $contact->title;
      $contact_email = $contact->field_email['und']['0']['email'];

      $contact_link = '';
      $options = array();
      $contact_link = l(t($contact_name), 'mailto:' . $contact_email, $options, array('attributes' => array('class' => array('contact-link'))));

      $contact_list .= $contact_link . $separator;
    }
  }
  return $contact_list;
}
