<?php
/**
 * @file
 * Code for the Cluster Events feature.
 */

include_once 'cluster_events.features.inc';
include_once 'cluster_events.pathauto.inc';

const CLUSTER_EVENTS_PER_PAGE = 10;

/**
 *  Implements hook_menu().
 */
function cluster_events_menu() {
  $items['node/%/events'] = array(
    'title' => 'events',
    'title callback' => '_cluster_events_title_callback',
    'title arguments' => array(1),
    'page callback' => 'cluster_events_all',
    'page arguments' => array(1),
    'access callback' => 'og_is_group',
    'access arguments' => array(0, 1),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu title callback.
 */
function _cluster_events_title_callback($nid) {
  global $language;
  $title = t('Events');
  if (! is_numeric($nid)) {
    return $title;
  }

  try {
    // @TODO manage multilinigual loading of entities.
    $wrapper = entity_metadata_wrapper('node', node_load($nid), array('langcode' => LANGUAGE_NONE));
    return $wrapper->label();
  }
  catch (EntityMetadataWrapperException $exc) {
    _log_entity_metadata_wrapper_error($exc, 'cluster_context');
  }
  return $title;
}

/**
 * Page callback, shows a group's events using Search API.
 * @param $nid
 * @return Render array
 */
function cluster_events_all($nid) {
  $query = search_api_query('default_node_index');

  $filter = $query->createFilter();
  $filter->condition('og_group_ref', $nid);
  $filter->condition('type', 'event');
  $query->filter($filter);

  $offset = pager_find_page() * CLUSTER_EVENTS_PER_PAGE;
  $query->range($offset, CLUSTER_EVENTS_PER_PAGE);

  $result = $query->execute();
  pager_default_initialize($result['result count'], CLUSTER_EVENTS_PER_PAGE);

  if (! $result['results']) {
    $content = array(
      '#markup' => t('No events scheduled at the moment.'),
    );
  }
  else {
    $content = node_view_multiple(node_load_multiple(array_keys($result['results'])));
  }

  $ret['content'] = $content;
  $ret['pager'] = array(
    '#theme' => 'pager',
  );

  return $ret;
}

/**
 * Implements hook_theme().
 */
function cluster_events_theme() {
  return array(
    'cluster_events_all' => array(
      'file' => 'theme/cluster_events.theme.inc',
      'render element' => 'element',
    ),
    'cluster_events_teaser' => array(
      'file' => 'theme/cluster_events.theme.inc',
      'render element' => 'element',
    ),
    'cluster_events_upcoming' => array(
      'file' => 'theme/cluster_events.theme.inc',
      'render element' => 'element',
    ),
  );
}

/**
 * Implements hook_node_view_alter().
 */
function cluster_events_node_view_alter(&$build) {
  if ($build['#node']->type != 'event') {
    return;
  }
  switch ($build['#view_mode']) {
    case 'teaser':
      $build['#theme'] = 'cluster_events_teaser';

      break;
    default:
      // Do nothing.
  }
}

function cluster_events_upcoming() {
  $query = new EntityFieldQuery();
  $results = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'event')
    ->fieldCondition('field_event_date', 'value', date('Y-m-d'), '>')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldOrderBy('field_event_date', 'value')
    ->range(0, 5)
    ->execute();

  if (!isset($results['node'])) {
    return FALSE;
  }

  $nids = array_keys($results['node']);

  $entities = entity_load('node', $nids);
  $ret = array(
    '#theme_wrappers' => array('cluster_events_upcoming'),
    '#total' => count($nids),
  );
  foreach ($entities as $entity) {
    $ret[$entity->nid] = cluster_events_format_upcoming($entity->nid, FALSE);
  }

  return $ret;
}

function cluster_events_format_upcoming($nid, $single_display = TRUE) {
  $node = node_load($nid);
  if (!$node || $node->type != 'event') {
    return FALSE;
  }

  $wrapper = entity_metadata_wrapper('node', $node);

  $value = $wrapper->field_event_date->value();
  $from = strtotime($value['value']);
  $to   = strtotime($value['value2']);
  $format      = 'M. j' . '\<\s\u\p\>' . 'S' . '\<\/\s\u\p\>' . ' Y';
  $format_from = 'M. j' . '\<\s\u\p\>' . 'S' . '\<\/\s\u\p\>';
  $format_to   = 'M. j' . '\<\s\u\p\>' . 'S' . '\<\/\s\u\p\>' . ' Y';
  if ($to > $from) {
    $date = date($format_from, $from);
    $date .= ' to ' . date($format_to, $to);
  }
  else {
    $date = date($format, $from);
  }

  if ($single_display) {
    $group_ref = $wrapper->og_group_ref->value();
    return array(
      '#theme' => 'cluster_og_upcoming_event',
      '#all_events_link' => 'node/' . $group_ref[0]->nid . '/events',
      '#event_title' => $wrapper->title->value(),
      '#event_link' => 'node/' . $node->nid,
      '#event_date' => $date,
    );
  }
  else {
    return array(
      '#theme' => 'link',
      '#text' => $date . ': ' . t($wrapper->title->value()),
      '#path' => 'node/' . $node->nid,
      '#options' => array(
        'attributes' => array(),
        'html' => TRUE,
      ),
    );
  }
}
