<?php

/**
 * Implements hook_menu().
 */
function shelter_migrate_menu() {
  return array(
    'admin/config/content/shelter-migrate' => array(
      'title' => 'Migration configuration',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shelter_migrate_admin_form'),
      'access arguments' => array('administer site configuration'),
    ),
    'admin/content/shelter-migrate' => array(
      'title' => 'Migrate from sheltercluster.org',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shelter_migrate_form'),
      'access arguments' => array('administer site configuration'),
    ),
    'node/%node/shelter-migrate' => array(
      'title' => 'Migrate docs from sheltercluster.org',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('shelter_migrate_node_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'shelter_migrate.node.inc',
      'weight' => 10,
    ),
  );
}

function shelter_migrate_admin_form($form, &$form_state) {
  $form['shelter_resources_nid'] = array(
    '#type' => 'textfield',
    '#title' => t('Resources group nid'),
    '#description' => t('Enter the node ID for the Resources group. This should belong to a Working Group.'),
    '#default_value' => variable_get('shelter_resources_nid'),
  );

  return system_settings_form($form);
}

/**
 * Generates the main form for migration operations.
 */
function shelter_migrate_form($form, &$form_state) {
  if (!shelter_migrate_get_resources_nid()) {
    drupal_set_message('Resources group not defined yet.', 'error');
    drupal_goto('admin/config/content/shelter-migrate', array(
      'query' => array('destination' => current_path()),
    ));
  }

  $form['alert'] = array(
    '#theme' => 'html_tag',
    '#tag' => 'div',
    '#value' => t('This page contains very dangerous operations, be careful!'),
    '#attributes' => array('class' => 'messages warning'),
  );

//  $form['delete_all_content'] = array(
//    '#type' => 'submit',
//    '#name' => 'delete_all_content',
//    '#value' => t('Delete all content from the site'),
//  );

  $form['import_regions_responses'] = array(
    '#type' => 'submit',
    '#name' => 'import_regions_responses',
    '#value' => t('Import all regions and responses'),
  );

  $form['import_all_docs'] = array(
    '#type' => 'submit',
    '#name' => 'import_all_docs',
    '#value' => t('Import documents for all groups (can be called multiple times)'),
  );

  return $form;
}

function shelter_migrate_form_submit($form, &$form_state) {
  try {
    switch ($form_state['triggering_element']['#name']) {
      case 'delete_all_content':
        drupal_set_message('Not implemented yet.', 'error');
        break;
      case 'import_regions_responses':
        require_once 'includes/import_regions_responses.inc';
        drupal_set_message(_shelter_migrate_import_regions_responses());
        break;
      case 'import_all_docs':
        require_once 'includes/batch_documents.inc';
        _shelter_migrate_batch_documents();
        break;
    }
  } catch (Exception $e) {
    if (function_exists('dpm')) {
      dpm($e, 'Exception');
    }
    drupal_set_message($e->getMessage(), 'error');
  }
}

function shelter_migrate_get_resources_nid() {
  $nid = intval(variable_get('shelter_resources_nid'));
  if (!$nid) {
    return FALSE;
  }

  $node = node_load($nid);
  return $node && $node->type == 'working_group' ? $nid : FALSE;
}
