<?php
/**
 * @file
 * Code for the cluster_libraries feature.
 */

include_once 'cluster_libraries.features.inc';
include_once 'cluster_libraries.vbo.inc';

/**
 * Implements hook_node_view_alter().
 * 
 * Creates a document table list and appends it to the page content.
 * Most of the logic of this function has to do with applying filters to the
 * Search API query based on the library's configuration.
 * Depending on the content type, different filters will be applied to the query.
 */
function cluster_libraries_node_view_alter(&$build) {
  $node = $build['#node'];
  $valid_types = array('library', 'arbitrary_library');
  if (! in_array($node->type, $valid_types) || $build['#view_mode'] != 'full') {
    return;
  }

  $query = cluster_docs_query();

  $wrapper = entity_metadata_wrapper('node', $node);

  // Facets are excluded from view if (and only if) there is exactly ONE value
  // selected in the corresponding field.
  $excluded_facets = array();

  switch ($node->type) {
    case 'library' :
      if (!$wrapper->field_is_global_library->value() && $groups = $wrapper->og_group_ref->value()) {
        $filter = $query->createFilter();
        foreach ($groups as $group) {
          $filter->condition('og_group_ref', $group->nid);
        }
        $query->filter($filter);
      }

      $fields = cluster_docs_taxonomies();
      foreach ($fields as $field) {
        if (!isset($node->$field)) {
          continue;
        }

        $value = $wrapper->$field->value();

        if (!$value) {
          continue;
        }

        $filter = $query->createFilter();
        foreach ($value as $term) {
          $filter->condition($field, $term->tid);
        }
        $query->filter($filter);

        if (count($value) == 1) {
          $excluded_facets[] = $field;
        }
      }
    break;
    case 'arbitrary_library':
      $filter = $query->createFilter();
      $filter->condition('nid', $wrapper->field_arbitrary_document_ref->raw(), 'IN');
      $query->filter($filter);
    break;
  }

  $build[] = cluster_docs_page($query, TRUE, 'title', 'ASC', $excluded_facets);
}
